'use client';

import { useMemo } from 'react';
import type { Shot, YardageCardConfig, EnvironmentConditions } from '@/lib/types';
import { computeCardClubs } from './YardageCardPreview';

interface Props {
  shots: Shot[];
  config: YardageCardConfig;
  sessionEnv?: EnvironmentConditions | null;
  destEnv?: EnvironmentConditions | null;
}

/**
 * Generates a yardage card PDF using @react-pdf/renderer.
 * Dynamically imported to avoid SSR issues.
 */
export default function YardageCardPDFButton({ shots, config, sessionEnv, destEnv }: Props) {
  const clubs = useMemo(
    () => computeCardClubs(shots, config, sessionEnv, destEnv),
    [shots, config, sessionEnv, destEnv]
  );

  const handleExport = async () => {
    // Dynamic import to avoid SSR issues with react-pdf
    const { Document, Page, Text, View, StyleSheet, pdf } = await import('@react-pdf/renderer');

    const styles = StyleSheet.create({
      page: {
        padding: 16,
        backgroundColor: '#111827',
      },
      title: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#4ade80',
        textAlign: 'center',
        marginBottom: 4,
      },
      subtitle: {
        fontSize: 7,
        color: '#9ca3af',
        textAlign: 'center',
        marginBottom: 8,
      },
      headerRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#374151',
        paddingBottom: 3,
        marginBottom: 3,
      },
      row: {
        flexDirection: 'row',
        borderBottomWidth: 0.5,
        borderBottomColor: '#1f2937',
        paddingVertical: 2,
      },
      cellClub: { width: '20%', fontSize: 8, color: '#e5e7eb', fontWeight: 'bold' },
      cellCarry: { width: '18%', fontSize: 8, color: '#d1d5db', textAlign: 'center' },
      cellTotal: { width: '18%', fontSize: 8, color: '#9ca3af', textAlign: 'center' },
      cellGap: { width: '10%', fontSize: 8, color: '#6b7280', textAlign: 'center' },
      cellTend: { width: '15%', fontSize: 8, textAlign: 'center' },
      cellConf: { width: '10%', fontSize: 8, textAlign: 'center' },
      cellN: { width: '9%', fontSize: 8, color: '#6b7280', textAlign: 'center' },
      headerText: { fontSize: 7, color: '#6b7280', textTransform: 'uppercase' },
      footer: { fontSize: 6, color: '#4b5563', textAlign: 'center', marginTop: 6 },
    });

    const bandLabel = config.percentileBand === 'P10-P90' ? 'P10-P90' : 'P20-P80';

    const doc = (
      <Document>
        <Page size={[252, 360]} style={styles.page}>
          <Text style={styles.title}>Yardage Card</Text>
          <Text style={styles.subtitle}>
            {bandLabel} | {config.fullShotsOnly ? 'Full shots' : 'All shots'}
          </Text>

          <View style={styles.headerRow}>
            <Text style={[styles.cellClub, styles.headerText]}>Club</Text>
            <Text style={[styles.cellCarry, styles.headerText]}>Carry</Text>
            <Text style={[styles.cellTotal, styles.headerText]}>Total</Text>
            {config.showGaps && <Text style={[styles.cellGap, styles.headerText]}>Gap</Text>}
            {config.showTendency && <Text style={[styles.cellTend, styles.headerText]}>Tend</Text>}
            {config.showConfidence && <Text style={[styles.cellConf, styles.headerText]}>Conf</Text>}
            <Text style={[styles.cellN, styles.headerText]}>n</Text>
          </View>

          {clubs.map((club) => (
            <View key={club.clubName} style={styles.row}>
              <Text style={styles.cellClub}>{club.clubName}</Text>
              <Text style={styles.cellCarry}>
                {club.carryRange[0]}-{club.carryRange[1]}
              </Text>
              <Text style={styles.cellTotal}>
                {club.totalRange[0]}-{club.totalRange[1]}
              </Text>
              {config.showGaps && (
                <Text style={styles.cellGap}>
                  {club.gapToNext != null ? String(club.gapToNext) : '-'}
                </Text>
              )}
              {config.showTendency && (
                <Text style={[styles.cellTend, { color: club.tendency > 0.5 ? '#facc15' : club.tendency < -0.5 ? '#60a5fa' : '#6b7280' }]}>
                  {club.tendencyLabel}
                </Text>
              )}
              {config.showConfidence && (
                <Text style={[styles.cellConf, {
                  color: club.confidence === 'High' ? '#4ade80' : club.confidence === 'Med' ? '#facc15' : '#f87171'
                }]}>
                  {club.confidence}
                </Text>
              )}
              <Text style={styles.cellN}>{String(club.n)}</Text>
            </View>
          ))}

          <Text style={styles.footer}>Generated by The Golf Lab</Text>
        </Page>
      </Document>
    );

    try {
      const blob = await pdf(doc).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'yardage-card.pdf';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
  };

  return (
    <button
      onClick={handleExport}
      className="px-3 py-1 text-xs bg-gray-800 hover:bg-gray-700 rounded text-gray-300"
    >
      Export PDF
    </button>
  );
}
