'use client';

import { useMemo } from 'react';
import type { Shot, YardageCardConfig, EnvironmentConditions } from '@/lib/types';
import { computeCardClubs } from './YardageCardPreview';

interface Props {
  shots: Shot[];
  config: YardageCardConfig;
  sessionEnv?: EnvironmentConditions | null;
  destEnv?: EnvironmentConditions | null;
}

/**
 * Generates a yardage card PDF using @react-pdf/renderer.
 * Dynamically imported to avoid SSR issues.
 */
export default function YardageCardPDFButton({ shots, config, sessionEnv, destEnv }: Props) {
  const clubs = useMemo(
    () => computeCardClubs(shots, config, sessionEnv, destEnv),
    [shots, config, sessionEnv, destEnv]
  );

  const handleExport = async () => {
    // Dynamic import to avoid SSR issues with react-pdf
    const { Document, Page, Text, View, StyleSheet, pdf } = await import('@react-pdf/renderer');

    // Count optional columns to distribute widths
    const optCols = [config.showGaps, config.showDispersionArc, config.showTendency].filter(Boolean).length;
    // Base columns: Club(20%) + Carry(20%) + Total(20%) = 60%
    // Remaining 40% distributed among optional columns
    const optWidth = optCols > 0 ? `${Math.floor(40 / optCols)}%` : '0%';

    const styles = StyleSheet.create({
      page: {
        padding: 12,
        backgroundColor: '#111827',
      },
      title: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#4ade80',
        textAlign: 'center',
        marginBottom: 2,
      },
      subtitle: {
        fontSize: 6,
        color: '#9ca3af',
        textAlign: 'center',
        marginBottom: 6,
      },
      headerRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#374151',
        paddingBottom: 2,
        marginBottom: 2,
      },
      row: {
        flexDirection: 'row',
        borderBottomWidth: 0.5,
        borderBottomColor: '#1f2937',
        paddingVertical: 1.5,
      },
      cellClub: { width: '20%', fontSize: 7, color: '#e5e7eb', fontWeight: 'bold' },
      cellCarry: { width: '20%', fontSize: 7, color: '#d1d5db', textAlign: 'center' },
      cellTotal: { width: '20%', fontSize: 7, color: '#9ca3af', textAlign: 'center' },
      cellOpt: { width: optWidth, fontSize: 7, textAlign: 'center' },
      headerText: { fontSize: 6, color: '#6b7280', textTransform: 'uppercase' },
      footer: { fontSize: 5, color: '#4b5563', textAlign: 'center', marginTop: 4 },
    });

    const bandLabel = config.percentileBand === 'P10-P90' ? 'P10-P90' : 'P20-P80';

    const doc = (
      <Document>
        <Page size={[288, 432]} style={styles.page}>
          <Text style={styles.title}>Yardage Card</Text>
          <Text style={styles.subtitle}>
            {bandLabel} | {config.fullShotsOnly ? 'Full shots' : 'All shots'}
          </Text>

          <View style={styles.headerRow}>
            <Text style={[styles.cellClub, styles.headerText]}>Club</Text>
            <Text style={[styles.cellCarry, styles.headerText]}>Carry</Text>
            <Text style={[styles.cellTotal, styles.headerText]}>Total</Text>
            {config.showGaps && <Text style={[styles.cellOpt, styles.headerText]}>Gap</Text>}
            {config.showDispersionArc && <Text style={[styles.cellOpt, styles.headerText]}>Disp</Text>}
            {config.showTendency && <Text style={[styles.cellOpt, styles.headerText]}>Tend</Text>}
          </View>

          {clubs.map((club) => (
            <View key={club.clubName} style={styles.row}>
              <Text style={styles.cellClub}>{club.clubName}</Text>
              <Text style={styles.cellCarry}>
                {club.carryRange[0]}-{club.carryRange[1]}
              </Text>
              <Text style={styles.cellTotal}>
                {club.totalRange[0]}-{club.totalRange[1]}
              </Text>
              {config.showGaps && (
                <Text style={[styles.cellOpt, { color: '#6b7280' }]}>
                  {club.gapToNext != null ? String(club.gapToNext) : '-'}
                </Text>
              )}
              {config.showDispersionArc && (
                <Text style={[styles.cellOpt, {
                  color: club.isDriver
                    ? (club.dispersionBias === 'R' ? '#facc15' : club.dispersionBias === 'L' ? '#60a5fa' : '#9ca3af')
                    : '#9ca3af'
                }]}>
                  {club.isDriver
                    ? `${club.dispersionArc} ${club.dispersionLeft}L-${club.dispersionRight}R`
                    : `${club.dispersionRadius}yd`
                  }
                </Text>
              )}
              {config.showTendency && (
                <Text style={[styles.cellOpt, { color: club.tendency > 0.5 ? '#facc15' : club.tendency < -0.5 ? '#60a5fa' : '#6b7280' }]}>
                  {club.tendencyLabel}
                </Text>
              )}
              {/* confidence and n hidden from card */}
            </View>
          ))}

          <Text style={styles.footer}>Generated by Golf OS</Text>
        </Page>
      </Document>
    );

    try {
      const blob = await pdf(doc).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'yardage-card.pdf';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
  };

  return (
    <button
      onClick={handleExport}
      className="px-3 py-1 text-xs bg-gray-800 hover:bg-gray-700 rounded text-gray-300"
    >
      Export PDF
    </button>
  );
}
